version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"  # MongoDB port
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: qm-feedback
    restart: "always"
    command: python manage.py runserver 0.0.0.0:8000
    # command: ["uwsgi", "--ini", "/code/uwsgi.ini"]
    # command: gunicorn qmeter.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    # environment:
      # - LANG=C.UTF-8
      # - LANG=en_US.UTF-8
      # - LANGUAGE=en_US:en
      # - LC_ALL=en_US.UTF-8
    depends_on:
      - "mongodb"


volumes:
  mongo_data:

